version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    networks:
      - thui-external
    volumes:
      - /data/assets/:/app/public/assets/
networks:
  thui-external:
    driver: bridge